server:
  port: 8999

spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  #Thymeleaf
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
